language: php

php:
  - 5.4

install:
  - composer install
  - composer require codeclimate/php-test-reporter:dev-master

before_script: mkdir -p build/logs

script: phpunit --configuration ./tests/phpunit.xml --coverage-clover ./build/logs/clover.xml
